//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.23 at 08:36:19 AM AEST 
//


package org.bom.forecast.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * This tag allows the AMOC metadata to be easily
 *       identified when it is embedded within a product formatted as XML or
 *       HTML.
 * 
 * <p>Java class for amocType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="amocType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="source" type="{}sourceType"/>
 *         &lt;element name="identifier" type="{}identifierType"/>
 *         &lt;element name="issue-time-utc" type="{}timestampType"/>
 *         &lt;element name="issue-time-local" type="{}timestampType"/>
 *         &lt;element name="sent-time" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="expiry-time" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="validity-bgn-time-local" type="{}timestampType" minOccurs="0"/>
 *         &lt;element name="validity-end-time-local" type="{}timestampType" minOccurs="0"/>
 *         &lt;element name="next-routine-issue-time-utc" type="{}timestampType" minOccurs="0"/>
 *         &lt;element name="next-routine-issue-time-local" type="{}timestampType" minOccurs="0"/>
 *         &lt;element name="status" type="{}statusType"/>
 *         &lt;element name="service" type="{}serviceType"/>
 *         &lt;element name="sub-service" type="{}sub-serviceType" minOccurs="0"/>
 *         &lt;element name="product-type" type="{}product-typeType"/>
 *         &lt;element name="phase" type="{}phaseType"/>
 *         &lt;element name="hazard" type="{}hazardType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="incident-id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" default="1.3" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "amocType", propOrder = {
    "source",
    "identifier",
    "issueTimeUtc",
    "issueTimeLocal",
    "sentTime",
    "expiryTime",
    "validityBgnTimeLocal",
    "validityEndTimeLocal",
    "nextRoutineIssueTimeUtc",
    "nextRoutineIssueTimeLocal",
    "status",
    "service",
    "subService",
    "productType",
    "phase",
    "hazard",
    "incidentId"
})
public class AmocType {

    @XmlElement(required = true)
    protected SourceType source;
    @XmlElement(required = true)
    protected String identifier;
    @XmlElement(name = "issue-time-utc", required = true)
    protected TimestampType issueTimeUtc;
    @XmlElement(name = "issue-time-local", required = true)
    protected TimestampType issueTimeLocal;
    @XmlElement(name = "sent-time", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar sentTime;
    @XmlElement(name = "expiry-time")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar expiryTime;
    @XmlElement(name = "validity-bgn-time-local")
    protected TimestampType validityBgnTimeLocal;
    @XmlElement(name = "validity-end-time-local")
    protected TimestampType validityEndTimeLocal;
    @XmlElement(name = "next-routine-issue-time-utc")
    protected TimestampType nextRoutineIssueTimeUtc;
    @XmlElement(name = "next-routine-issue-time-local")
    protected TimestampType nextRoutineIssueTimeLocal;
    @XmlElement(required = true)
    protected String status;
    @XmlElement(required = true)
    protected String service;
    @XmlElement(name = "sub-service")
    protected String subService;
    @XmlElement(name = "product-type", required = true)
    protected String productType;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected PhaseType phase;
    protected List<HazardType> hazard;
    @XmlElement(name = "incident-id")
    protected String incidentId;
    @XmlAttribute(name = "version")
    protected String version;

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link SourceType }
     *     
     */
    public SourceType getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceType }
     *     
     */
    public void setSource(SourceType value) {
        this.source = value;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifier(String value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the issueTimeUtc property.
     * 
     * @return
     *     possible object is
     *     {@link TimestampType }
     *     
     */
    public TimestampType getIssueTimeUtc() {
        return issueTimeUtc;
    }

    /**
     * Sets the value of the issueTimeUtc property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimestampType }
     *     
     */
    public void setIssueTimeUtc(TimestampType value) {
        this.issueTimeUtc = value;
    }

    /**
     * Gets the value of the issueTimeLocal property.
     * 
     * @return
     *     possible object is
     *     {@link TimestampType }
     *     
     */
    public TimestampType getIssueTimeLocal() {
        return issueTimeLocal;
    }

    /**
     * Sets the value of the issueTimeLocal property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimestampType }
     *     
     */
    public void setIssueTimeLocal(TimestampType value) {
        this.issueTimeLocal = value;
    }

    /**
     * Gets the value of the sentTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSentTime() {
        return sentTime;
    }

    /**
     * Sets the value of the sentTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSentTime(XMLGregorianCalendar value) {
        this.sentTime = value;
    }

    /**
     * Gets the value of the expiryTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpiryTime() {
        return expiryTime;
    }

    /**
     * Sets the value of the expiryTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpiryTime(XMLGregorianCalendar value) {
        this.expiryTime = value;
    }

    /**
     * Gets the value of the validityBgnTimeLocal property.
     * 
     * @return
     *     possible object is
     *     {@link TimestampType }
     *     
     */
    public TimestampType getValidityBgnTimeLocal() {
        return validityBgnTimeLocal;
    }

    /**
     * Sets the value of the validityBgnTimeLocal property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimestampType }
     *     
     */
    public void setValidityBgnTimeLocal(TimestampType value) {
        this.validityBgnTimeLocal = value;
    }

    /**
     * Gets the value of the validityEndTimeLocal property.
     * 
     * @return
     *     possible object is
     *     {@link TimestampType }
     *     
     */
    public TimestampType getValidityEndTimeLocal() {
        return validityEndTimeLocal;
    }

    /**
     * Sets the value of the validityEndTimeLocal property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimestampType }
     *     
     */
    public void setValidityEndTimeLocal(TimestampType value) {
        this.validityEndTimeLocal = value;
    }

    /**
     * Gets the value of the nextRoutineIssueTimeUtc property.
     * 
     * @return
     *     possible object is
     *     {@link TimestampType }
     *     
     */
    public TimestampType getNextRoutineIssueTimeUtc() {
        return nextRoutineIssueTimeUtc;
    }

    /**
     * Sets the value of the nextRoutineIssueTimeUtc property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimestampType }
     *     
     */
    public void setNextRoutineIssueTimeUtc(TimestampType value) {
        this.nextRoutineIssueTimeUtc = value;
    }

    /**
     * Gets the value of the nextRoutineIssueTimeLocal property.
     * 
     * @return
     *     possible object is
     *     {@link TimestampType }
     *     
     */
    public TimestampType getNextRoutineIssueTimeLocal() {
        return nextRoutineIssueTimeLocal;
    }

    /**
     * Sets the value of the nextRoutineIssueTimeLocal property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimestampType }
     *     
     */
    public void setNextRoutineIssueTimeLocal(TimestampType value) {
        this.nextRoutineIssueTimeLocal = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the service property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getService() {
        return service;
    }

    /**
     * Sets the value of the service property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setService(String value) {
        this.service = value;
    }

    /**
     * Gets the value of the subService property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubService() {
        return subService;
    }

    /**
     * Sets the value of the subService property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubService(String value) {
        this.subService = value;
    }

    /**
     * Gets the value of the productType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductType() {
        return productType;
    }

    /**
     * Sets the value of the productType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductType(String value) {
        this.productType = value;
    }

    /**
     * Gets the value of the phase property.
     * 
     * @return
     *     possible object is
     *     {@link PhaseType }
     *     
     */
    public PhaseType getPhase() {
        return phase;
    }

    /**
     * Sets the value of the phase property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhaseType }
     *     
     */
    public void setPhase(PhaseType value) {
        this.phase = value;
    }

    /**
     * Gets the value of the hazard property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hazard property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHazard().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HazardType }
     * 
     * 
     */
    public List<HazardType> getHazard() {
        if (hazard == null) {
            hazard = new ArrayList<HazardType>();
        }
        return this.hazard;
    }

    /**
     * Gets the value of the incidentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncidentId() {
        return incidentId;
    }

    /**
     * Sets the value of the incidentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncidentId(String value) {
        this.incidentId = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "1.3";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
