//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.23 at 08:36:19 AM AEST 
//


package org.bom.forecast.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for elementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="elementType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="units" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="instance" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sequence" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="duration" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="time-utc" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="time-local" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="start-time-utc" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="start-time-local" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="end-time-utc" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="end-time-local" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="start-month" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="end-month" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "elementType", propOrder = {
    "value"
})
public class ElementType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "type", required = true)
    protected String type;
    @XmlAttribute(name = "units")
    protected String units;
    @XmlAttribute(name = "instance")
    protected String instance;
    @XmlAttribute(name = "sequence")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger sequence;
    @XmlAttribute(name = "duration")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger duration;
    @XmlAttribute(name = "time-utc")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeUtc;
    @XmlAttribute(name = "time-local")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeLocal;
    @XmlAttribute(name = "start-time-utc")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startTimeUtc;
    @XmlAttribute(name = "start-time-local")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startTimeLocal;
    @XmlAttribute(name = "end-time-utc")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endTimeUtc;
    @XmlAttribute(name = "end-time-local")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endTimeLocal;
    @XmlAttribute(name = "start-month")
    protected String startMonth;
    @XmlAttribute(name = "end-month")
    protected String endMonth;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the units property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnits() {
        return units;
    }

    /**
     * Sets the value of the units property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnits(String value) {
        this.units = value;
    }

    /**
     * Gets the value of the instance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstance() {
        return instance;
    }

    /**
     * Sets the value of the instance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstance(String value) {
        this.instance = value;
    }

    /**
     * Gets the value of the sequence property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSequence() {
        return sequence;
    }

    /**
     * Sets the value of the sequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSequence(BigInteger value) {
        this.sequence = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDuration(BigInteger value) {
        this.duration = value;
    }

    /**
     * Gets the value of the timeUtc property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeUtc() {
        return timeUtc;
    }

    /**
     * Sets the value of the timeUtc property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeUtc(XMLGregorianCalendar value) {
        this.timeUtc = value;
    }

    /**
     * Gets the value of the timeLocal property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeLocal() {
        return timeLocal;
    }

    /**
     * Sets the value of the timeLocal property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeLocal(XMLGregorianCalendar value) {
        this.timeLocal = value;
    }

    /**
     * Gets the value of the startTimeUtc property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartTimeUtc() {
        return startTimeUtc;
    }

    /**
     * Sets the value of the startTimeUtc property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartTimeUtc(XMLGregorianCalendar value) {
        this.startTimeUtc = value;
    }

    /**
     * Gets the value of the startTimeLocal property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartTimeLocal() {
        return startTimeLocal;
    }

    /**
     * Sets the value of the startTimeLocal property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartTimeLocal(XMLGregorianCalendar value) {
        this.startTimeLocal = value;
    }

    /**
     * Gets the value of the endTimeUtc property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndTimeUtc() {
        return endTimeUtc;
    }

    /**
     * Sets the value of the endTimeUtc property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndTimeUtc(XMLGregorianCalendar value) {
        this.endTimeUtc = value;
    }

    /**
     * Gets the value of the endTimeLocal property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndTimeLocal() {
        return endTimeLocal;
    }

    /**
     * Sets the value of the endTimeLocal property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndTimeLocal(XMLGregorianCalendar value) {
        this.endTimeLocal = value;
    }

    /**
     * Gets the value of the startMonth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartMonth() {
        return startMonth;
    }

    /**
     * Sets the value of the startMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartMonth(String value) {
        this.startMonth = value;
    }

    /**
     * Gets the value of the endMonth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndMonth() {
        return endMonth;
    }

    /**
     * Sets the value of the endMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndMonth(String value) {
        this.endMonth = value;
    }

}
