//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.23 at 08:36:19 AM AEST 
//


package org.bom.forecast.jaxb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for forecast-periodType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="forecast-periodType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="warning-summary" type="{}periodic-warning-summaryType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="element" type="{}elementType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="text" type="{}text-elementType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="hazard" type="{}periodicHazardType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="index" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="end-index" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="index-tag" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="start-time-utc" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="start-time-local" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="end-time-utc" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="end-time-local" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="end-date-local" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "forecast-periodType", propOrder = {
    "warningSummaryOrElementOrText"
})
public class ForecastPeriodType {

    @XmlElements({
        @XmlElement(name = "warning-summary", type = PeriodicWarningSummaryType.class),
        @XmlElement(name = "element", type = ElementType.class),
        @XmlElement(name = "text", type = TextElementType.class),
        @XmlElement(name = "hazard", type = PeriodicHazardType.class)
    })
    protected List<Object> warningSummaryOrElementOrText;
    @XmlAttribute(name = "index")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger index;
    @XmlAttribute(name = "end-index")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger endIndex;
    @XmlAttribute(name = "index-tag")
    protected String indexTag;
    @XmlAttribute(name = "start-time-utc")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startTimeUtc;
    @XmlAttribute(name = "start-time-local", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startTimeLocal;
    @XmlAttribute(name = "end-time-utc")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endTimeUtc;
    @XmlAttribute(name = "end-time-local", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endTimeLocal;
    @XmlAttribute(name = "end-date-local")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endDateLocal;

    /**
     * Gets the value of the warningSummaryOrElementOrText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the warningSummaryOrElementOrText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWarningSummaryOrElementOrText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PeriodicWarningSummaryType }
     * {@link ElementType }
     * {@link TextElementType }
     * {@link PeriodicHazardType }
     * 
     * 
     */
    public List<Object> getWarningSummaryOrElementOrText() {
        if (warningSummaryOrElementOrText == null) {
            warningSummaryOrElementOrText = new ArrayList<Object>();
        }
        return this.warningSummaryOrElementOrText;
    }

    /**
     * Gets the value of the index property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIndex(BigInteger value) {
        this.index = value;
    }

    /**
     * Gets the value of the endIndex property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEndIndex() {
        return endIndex;
    }

    /**
     * Sets the value of the endIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEndIndex(BigInteger value) {
        this.endIndex = value;
    }

    /**
     * Gets the value of the indexTag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndexTag() {
        return indexTag;
    }

    /**
     * Sets the value of the indexTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndexTag(String value) {
        this.indexTag = value;
    }

    /**
     * Gets the value of the startTimeUtc property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartTimeUtc() {
        return startTimeUtc;
    }

    /**
     * Sets the value of the startTimeUtc property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartTimeUtc(XMLGregorianCalendar value) {
        this.startTimeUtc = value;
    }

    /**
     * Gets the value of the startTimeLocal property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartTimeLocal() {
        return startTimeLocal;
    }

    /**
     * Sets the value of the startTimeLocal property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartTimeLocal(XMLGregorianCalendar value) {
        this.startTimeLocal = value;
    }

    /**
     * Gets the value of the endTimeUtc property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndTimeUtc() {
        return endTimeUtc;
    }

    /**
     * Sets the value of the endTimeUtc property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndTimeUtc(XMLGregorianCalendar value) {
        this.endTimeUtc = value;
    }

    /**
     * Gets the value of the endTimeLocal property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndTimeLocal() {
        return endTimeLocal;
    }

    /**
     * Sets the value of the endTimeLocal property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndTimeLocal(XMLGregorianCalendar value) {
        this.endTimeLocal = value;
    }

    /**
     * Gets the value of the endDateLocal property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDateLocal() {
        return endDateLocal;
    }

    /**
     * Sets the value of the endDateLocal property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDateLocal(XMLGregorianCalendar value) {
        this.endDateLocal = value;
    }

}
