//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.23 at 08:36:19 AM AEST 
//


package org.bom.forecast.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for phaseType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="phaseType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="NEW"/>
 *     &lt;enumeration value="REN"/>
 *     &lt;enumeration value="UPD"/>
 *     &lt;enumeration value="DGD"/>
 *     &lt;enumeration value="UGD"/>
 *     &lt;enumeration value="FIN"/>
 *     &lt;enumeration value="CAN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "phaseType")
@XmlEnum
public enum PhaseType {

    NEW,
    REN,
    UPD,
    DGD,
    UGD,
    FIN,
    CAN;

    public String value() {
        return name();
    }

    public static PhaseType fromValue(String v) {
        return valueOf(v);
    }

}
