//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.23 at 08:36:19 AM AEST 
//


package org.bom.forecast.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for productType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="productType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="amoc" type="{}amocType"/>
 *         &lt;element name="warning" type="{}warningType" minOccurs="0"/>
 *         &lt;element name="forecast" type="{}forecastType" minOccurs="0"/>
 *         &lt;element name="warning-summaries" type="{}warning-summariesType" minOccurs="0"/>
 *         &lt;element name="observations" type="{}observationsType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" default="1.5" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "productType", propOrder = {
    "amoc",
    "warning",
    "forecast",
    "warningSummaries",
    "observations"
})
public class ProductType {

    @XmlElement(required = true)
    protected AmocType amoc;
    protected WarningType warning;
    protected ForecastType forecast;
    @XmlElement(name = "warning-summaries")
    protected WarningSummariesType warningSummaries;
    protected ObservationsType observations;
    @XmlAttribute(name = "version")
    protected String version;

    /**
     * Gets the value of the amoc property.
     * 
     * @return
     *     possible object is
     *     {@link AmocType }
     *     
     */
    public AmocType getAmoc() {
        return amoc;
    }

    /**
     * Sets the value of the amoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmocType }
     *     
     */
    public void setAmoc(AmocType value) {
        this.amoc = value;
    }

    /**
     * Gets the value of the warning property.
     * 
     * @return
     *     possible object is
     *     {@link WarningType }
     *     
     */
    public WarningType getWarning() {
        return warning;
    }

    /**
     * Sets the value of the warning property.
     * 
     * @param value
     *     allowed object is
     *     {@link WarningType }
     *     
     */
    public void setWarning(WarningType value) {
        this.warning = value;
    }

    /**
     * Gets the value of the forecast property.
     * 
     * @return
     *     possible object is
     *     {@link ForecastType }
     *     
     */
    public ForecastType getForecast() {
        return forecast;
    }

    /**
     * Sets the value of the forecast property.
     * 
     * @param value
     *     allowed object is
     *     {@link ForecastType }
     *     
     */
    public void setForecast(ForecastType value) {
        this.forecast = value;
    }

    /**
     * Gets the value of the warningSummaries property.
     * 
     * @return
     *     possible object is
     *     {@link WarningSummariesType }
     *     
     */
    public WarningSummariesType getWarningSummaries() {
        return warningSummaries;
    }

    /**
     * Sets the value of the warningSummaries property.
     * 
     * @param value
     *     allowed object is
     *     {@link WarningSummariesType }
     *     
     */
    public void setWarningSummaries(WarningSummariesType value) {
        this.warningSummaries = value;
    }

    /**
     * Gets the value of the observations property.
     * 
     * @return
     *     possible object is
     *     {@link ObservationsType }
     *     
     */
    public ObservationsType getObservations() {
        return observations;
    }

    /**
     * Sets the value of the observations property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObservationsType }
     *     
     */
    public void setObservations(ObservationsType value) {
        this.observations = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        if (version == null) {
            return "1.5";
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
