//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.23 at 08:36:19 AM AEST 
//


package org.bom.forecast.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for stationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="stationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="period" type="{}observation-periodType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="bom-id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="wmo-id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="aviation-id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="description" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tz" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="stn-name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="stn-height" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="owner" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="lat" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="lon" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="forecast-district-id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "stationType", propOrder = {
    "period"
})
public class StationType {

    protected List<ObservationPeriodType> period;
    @XmlAttribute(name = "bom-id")
    protected String bomId;
    @XmlAttribute(name = "wmo-id")
    protected String wmoId;
    @XmlAttribute(name = "aviation-id")
    protected String aviationId;
    @XmlAttribute(name = "description", required = true)
    protected String description;
    @XmlAttribute(name = "tz", required = true)
    protected String tz;
    @XmlAttribute(name = "stn-name")
    protected String stnName;
    @XmlAttribute(name = "stn-height")
    protected Float stnHeight;
    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "owner")
    protected String owner;
    @XmlAttribute(name = "lat", required = true)
    protected float lat;
    @XmlAttribute(name = "lon", required = true)
    protected float lon;
    @XmlAttribute(name = "forecast-district-id", required = true)
    protected String forecastDistrictId;

    /**
     * Gets the value of the period property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the period property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPeriod().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObservationPeriodType }
     * 
     * 
     */
    public List<ObservationPeriodType> getPeriod() {
        if (period == null) {
            period = new ArrayList<ObservationPeriodType>();
        }
        return this.period;
    }

    /**
     * Gets the value of the bomId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBomId() {
        return bomId;
    }

    /**
     * Sets the value of the bomId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBomId(String value) {
        this.bomId = value;
    }

    /**
     * Gets the value of the wmoId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWmoId() {
        return wmoId;
    }

    /**
     * Sets the value of the wmoId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWmoId(String value) {
        this.wmoId = value;
    }

    /**
     * Gets the value of the aviationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAviationId() {
        return aviationId;
    }

    /**
     * Sets the value of the aviationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAviationId(String value) {
        this.aviationId = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the tz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTz() {
        return tz;
    }

    /**
     * Sets the value of the tz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTz(String value) {
        this.tz = value;
    }

    /**
     * Gets the value of the stnName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStnName() {
        return stnName;
    }

    /**
     * Sets the value of the stnName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStnName(String value) {
        this.stnName = value;
    }

    /**
     * Gets the value of the stnHeight property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getStnHeight() {
        return stnHeight;
    }

    /**
     * Sets the value of the stnHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setStnHeight(Float value) {
        this.stnHeight = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwner(String value) {
        this.owner = value;
    }

    /**
     * Gets the value of the lat property.
     * 
     */
    public float getLat() {
        return lat;
    }

    /**
     * Sets the value of the lat property.
     * 
     */
    public void setLat(float value) {
        this.lat = value;
    }

    /**
     * Gets the value of the lon property.
     * 
     */
    public float getLon() {
        return lon;
    }

    /**
     * Sets the value of the lon property.
     * 
     */
    public void setLon(float value) {
        this.lon = value;
    }

    /**
     * Gets the value of the forecastDistrictId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForecastDistrictId() {
        return forecastDistrictId;
    }

    /**
     * Sets the value of the forecastDistrictId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForecastDistrictId(String value) {
        this.forecastDistrictId = value;
    }

}
