//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.23 at 08:36:19 AM AEST 
//


package org.bom.forecast.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for warningType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="warningType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="warning-info" type="{}warning-infoType"/>
 *         &lt;element name="area" type="{}areaType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "warningType", propOrder = {
    "warningInfo",
    "area"
})
public class WarningType {

    @XmlElement(name = "warning-info", required = true)
    protected WarningInfoType warningInfo;
    protected List<AreaType> area;

    /**
     * Gets the value of the warningInfo property.
     * 
     * @return
     *     possible object is
     *     {@link WarningInfoType }
     *     
     */
    public WarningInfoType getWarningInfo() {
        return warningInfo;
    }

    /**
     * Sets the value of the warningInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link WarningInfoType }
     *     
     */
    public void setWarningInfo(WarningInfoType value) {
        this.warningInfo = value;
    }

    /**
     * Gets the value of the area property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the area property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArea().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AreaType }
     * 
     * 
     */
    public List<AreaType> getArea() {
        if (area == null) {
            area = new ArrayList<AreaType>();
        }
        return this.area;
    }

}
